# Generated by Django 6.0.5 on 2026-05-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_department_userprogress_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='rank',
            field=models.CharField(blank=True, choices=[('', '-- Цолоо сонгоно уу --'), ('Цэрэг', 'Цэрэг'), ('Ефрейтор', 'Ефрейтор'), ('Жанжин дэд', 'Жанжин дэд'), ('Дэд ахлагч', 'Дэд ахлагч'), ('Ахлагч', 'Ахлагч'), ('Ахлах ахлагч', 'Ахлах ахлагч'), ('Дэд офицер', 'Дэд офицер'), ('Дэд дэслэгч', 'Дэд дэслэгч'), ('Дэслэгч', 'Дэслэгч'), ('Ахлах дэслэгч', 'Ахлах дэслэгч'), ('Капитан', 'Капитан'), ('Майор', 'Майор'), ('Дэд хурандаа', 'Дэд хурандаа'), ('Хурандаа', 'Хурандаа'), ('Бригадын генерал', 'Бригадын генерал'), ('Хошууч генерал', 'Хошууч генерал'), ('Генерал лейтенант', 'Генерал лейтенант'), ('Генерал полковник', 'Генерал полковник'), ('Бусад', 'Бусад')], max_length=100),
        ),
    ]
