# Generated by Django 6.0.5 on 2026-05-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_userprogress_full_name_userprogress_profile_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='study_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='rank',
            field=models.CharField(blank=True, choices=[('', '-- Цолоо сонгоно уу --'), ('Энгийн | Private', 'Энгийн | Private'), ('Дэд ахлагч | Corporal', 'Дэд ахлагч | Corporal'), ('Ахлагч | Sergeant', 'Ахлагч | Sergeant'), ('Ахлах ахлагч | Staff Sergeant', 'Ахлах ахлагч | Staff Sergeant'), ('Дэслэгч | Lieutenant', 'Дэслэгч | Lieutenant'), ('Ахлах дэслэгч | Senior Lieutenant', 'Ахлах дэслэгч | Senior Lieutenant'), ('Ахмад | Captain', 'Ахмад | Captain'), ('Хошууч | Major', 'Хошууч | Major'), ('Дэд хурандаа | Lieutenant Colonel', 'Дэд хурандаа | Lieutenant Colonel'), ('Хурандаа | Colonel', 'Хурандаа | Colonel'), ('Бригадын генерал | Brigadier General', 'Бригадын генерал | Brigadier General')], max_length=100),
        ),
    ]
