# Generated by Django 6.0.5 on 2026-05-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_userprogress_study_minutes_alter_userprogress_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Гарчиг')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('youtube_id', models.CharField(help_text='YouTube URL-аас авна. Жишээ: youtu.be/dQw4w9WgXcQ → dQw4w9WgXcQ', max_length=20, verbose_name='YouTube видео ID')),
                ('order', models.IntegerField(default=0, verbose_name='Дараалал')),
                ('is_published', models.BooleanField(default=True, verbose_name='Нийтлэгдсэн')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеонууд',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='rank',
            field=models.CharField(blank=True, choices=[('', '-- Цолоо сонгоно уу --'), ('Энгийн | Civilian', 'Энгийн | Civilian'), ('Дэд ахлагч | Junior Sergeant', 'Дэд ахлагч | Junior Sergeant'), ('Ахлагч | Sergeant', 'Ахлагч | Sergeant'), ('Ахлах ахлагч | Senior Sergeant', 'Ахлах ахлагч | Senior Sergeant'), ('Дэслэгч | Second Lieutenant', 'Дэслэгч | Second Lieutenant'), ('Ахлах дэслэгч | First Lieutenant', 'Ахлах дэслэгч | First Lieutenant'), ('Ахмад | Captain', 'Ахмад | Captain'), ('Хошууч | Major', 'Хошууч | Major'), ('Дэд хурандаа | Lieutenant Colonel', 'Дэд хурандаа | Lieutenant Colonel'), ('Хурандаа | Colonel', 'Хурандаа | Colonel'), ('Бригадын генерал | Brigadier General', 'Бригадын генерал | Brigadier General')], max_length=100),
        ),
    ]
